---
title: "股票分析-存股"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny

---

```{r setup, include=FALSE}

library(d3heatmap)
library(flexdashboard)
library(scales)
library(DT)
library(shiny)
library(XML)
library(RCurl)
library(httr)

(WD <- getwd())
setwd(WD)
final_pic <- read.csv("final_result.csv")
stock_price <- read.csv("stock_price.csv",row.names = 1)
colnames(final_pic)<-c("number","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016")
rownames(final_pic)<-final_pic[,1]
options(digits=5)
#stock_list<-merge(final_pic,stock_number,by="number")
#stock_list<-stock_list[order(-stock_list$`2016`),]
```
top 1-20
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------
### Stock heatmap 

```{r}
palette <- c("lightblue", "cornflowerblue", "mediumblue","midnightblue","hotpink","firebrick")
# breaks <- c(0,5,10,15,20,25,31)
# colorFunc <- col_bin(palette, bins = rescale(breaks)) # color function
d3heatmap(final_pic[1:20,2:11], scale = "column",dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stock list 

```{r}
knitr::kable(stock_price[1:20,1:3],row.names = F,align = "l")
```

top 21-40
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------
### Stock heatmap 

```{r}

d3heatmap(final_pic[21:40,2:11], scale = "column",dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stock list 

```{r}
knitr::kable(stock_price[21:40,1:3],row.names = F,align = "l")
```

top 41-60
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------
### Stock heatmap  

```{r}

d3heatmap(final_pic[41:60,2:11], scale = "column",dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stock list 

```{r}
knitr::kable(stock_price[41:60,1:3],row.names = F,align = "l")
```

top 61-80
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------
### Stock heatmap 

```{r}

d3heatmap(final_pic[61:80,2:11], scale = "column",dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stock list 

```{r}
knitr::kable(stock_price[61:80,1:3],row.names = F,align = "l")
```

top 81-100
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------
### Stock heatmap 

```{r}
d3heatmap(final_pic[81:100,2:11], scale = "column",dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stock list 

```{r}
knitr::kable(stock_price[81:100,1:3],row.names = F,align = "l")
```

查詢頁面
=======================================================================
### 建議股東報酬率>15%，本益比<15，董監事持股率>25%，負債比<55%

```{r}
datatable(stock_price,filter = "top")
```

個股探索
=======================================================================
Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
 numericInput("stocknumber",label = "股票代號",value = 8429)
```

Row 
-----------------------------------------------------------------------
### 股票名稱
```{r}
num<-reactive((input$stocknumber))
renderValueBox({
  valueBox(
    value = stock_price[stock_price[,1]==num(),2],icon = icon("filter"))
})
```

### 主要業務

```{r}
urll <- reactive(paste('http://www.wantgoo.com/Stock/aStock/Basic?StockNo=',num(),sep=''))
get_urll = reactive(getURL(urll(),encoding = "UTF-8"))
get_url_parsee = reactive(htmlParse(get_urll(), encoding = "UTF-8"))
work <- reactive(xpathSApply(get_url_parsee(), "/html/body/div[@id='wrap']/div[@id='container']/div[@id='mainCol']/div[@class='astk-basic br-trl']/table[@class='tb-vl'][1]/tbody/tr[10]/td", xmlValue))
renderText(as.character(work()))
# renderValueBox({
#   valueBox(
#     value = work(),icon = icon("filter"))
# })
```

### 歷年獲利浮動

```{r}


renderValueBox({

  

  valueBox(
    value = sd(final_pic[final_pic$number==num(),2:11],na.rm =T),icon = icon("table"))
    

})
```

### 除權漲跌幅

```{r}
url <- reactive(paste('http://www.wantgoo.com/Stock/report/basic_dp?StockNo=',num(),sep=''))
get_url = reactive(getURL(url(),encoding = "UTF-8"))
get_url_parse = reactive(htmlParse(get_url(), encoding = "UTF-8"))
price1 <- reactive(xpathSApply(get_url_parse(), "/html/body/div[@id='wrap']/div[@id='container']/div[@id='mainCol']/div[@class='br-trl']/table[@class='tb rw5n tbhl']/tbody/tr[1]/td[5]", xmlValue))
price2 <- reactive(xpathSApply(get_url_parse(), "/html/body/div[@id='wrap']/div[@id='container']/div[@id='mainCol']/div[@class='br-trl']/table[@class='tb rw5n tbhl']/tbody/tr[2]/td[5]", xmlValue))
renderValueBox({
  valueBox(
    value = (as.numeric(price1())-as.numeric(price2()))/as.numeric(price2())*100,icon = icon("filter"))
})
```

### 歷年配股配息

```{r}
renderTable(final_pic[final_pic$number==num(),2:11])
```

